import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import BottomBar from '@/components/BottomBar';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div id='playerCard'></div>
                <div id='errorMessage'></div>
                <div id='root'></div>
                {/* <Navbar /> */}
                <main className='App overflow-hidden bg-gradient-to-r from-[#6fcf48] to-[#94e9ad] min-h-screen'>
                    <main className='p-3 lg:max-w-md mx-auto mb-10'>
                        {children}
                    </main>
                </main>
                <BottomBar />
            </body>
        </html>
    );
}
